version: '3.8'

services:
  valuecell:
    image: zcleexx/valuecell:latest
    container_name: valuecell
    restart: always
    ports:
      - "9000:8000"
      - "8081:1420"
    volumes:
      - ./.env:/root/.config/valuecell/.env
      - ./data:/app/data
    environment:
      - API_HOST=69.63.216.212
      - API_PORT=9000
      - VITE_API_BASE_URL=http://69.63.216.212:9000
      - DISABLE_STDIN_CONTROL=true
